/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VFeriado extends javax.swing.JFrame {

    /**
     * Creates new form VCalendario
     */
    public VFeriado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelcalendario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jDateChooserferiado = new com.toedter.calendar.JDateChooser();
        jButtonBuscar = new javax.swing.JButton();
        jButtonregistrar = new javax.swing.JButton();
        jButtonmodificar = new javax.swing.JButton();
        jButtoneliminar = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelcalendario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Fecha:");

        jLabel2.setText("Descripción: ");

        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });

        jDateChooserferiado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooserferiadoKeyTyped(evt);
            }
        });

        jButtonBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanelcalendarioLayout = new javax.swing.GroupLayout(jPanelcalendario);
        jPanelcalendario.setLayout(jPanelcalendarioLayout);
        jPanelcalendarioLayout.setHorizontalGroup(
            jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcalendarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelcalendarioLayout.createSequentialGroup()
                        .addComponent(jDateChooserferiado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar))
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelcalendarioLayout.setVerticalGroup(
            jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcalendarioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooserferiado, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(jButtonBuscar))
                .addGap(40, 40, 40)
                .addGroup(jPanelcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jButtonregistrar.setText("Registrar");

        jButtonmodificar.setText("Modificar");

        jButtoneliminar.setText("Eliminar");

        jButtoncancelar.setText("Cancelar");

        jButtonsalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButtonregistrar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonmodificar)
                        .addGap(27, 27, 27)
                        .addComponent(jButtoneliminar)
                        .addGap(22, 22, 22)
                        .addComponent(jButtoncancelar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanelcalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonregistrar)
                    .addComponent(jButtonmodificar)
                    .addComponent(jButtoneliminar)
                    .addComponent(jButtoncancelar)
                    .addComponent(jButtonsalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanelcalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(755, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jDateChooserferiadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserferiadoKeyTyped
        this.enable(false);
    }//GEN-LAST:event_jDateChooserferiadoKeyTyped

   public JTextField getjTextFieldDescripcion() {
       
       return jTextFieldDescripcion;      
   }
 //-----------------------------
   public JDateChooser getJDateChooserFeriado(){
       
       return jDateChooserferiado;
   }
 //------------------------------        
   public JButton getjButtonCancelar()
    {
        return jButtoncancelar;
    }

//-------------------------------
    public JButton getjButtonRegistar() 
    {
        return jButtonregistrar;
    }
//-----------------------------
    public JButton getjButtonSalir() 
    {
        return jButtonsalir;
    }
//-------------------------------
     public JButton getjButtonModificar() 
    {
        return jButtonmodificar;
    }
//--------------------

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }
     
//-------------------------------
    public JButton getjButtonEliminar() 
    {
        return jButtoneliminar;
    }
   public void agregarActionListener(ActionListener accion){
       
       this.jButtonregistrar.addActionListener(accion);
       this.jButtonmodificar.addActionListener(accion);
       this.jButtoncancelar.addActionListener(accion);
       this.jButtoneliminar.addActionListener(accion);
       this.jButtonsalir.addActionListener(accion);
       
       this.jButtonBuscar.addActionListener(accion);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtoneliminar;
    private javax.swing.JButton jButtonmodificar;
    private javax.swing.JButton jButtonregistrar;
    private javax.swing.JButton jButtonsalir;
    private com.toedter.calendar.JDateChooser jDateChooserferiado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelcalendario;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
