/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author Usuario
 */
public class VMenuPrin extends javax.swing.JFrame {

    /**
     * Creates new form VMenuPrin
     */
    public VMenuPrin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuproyectos = new javax.swing.JMenu();
        jMenuItemgestproyectos = new javax.swing.JMenuItem();
        jMenuItemgestclientes = new javax.swing.JMenuItem();
        jMenuItemAsigCand = new javax.swing.JMenuItem();
        jMenucandidato = new javax.swing.JMenu();
        jMenuItemgestcandidato = new javax.swing.JMenuItem();
        jMenuItemgestentrevistas = new javax.swing.JMenuItem();
        jMenuempleados = new javax.swing.JMenu();
        jMenuItemregnomina = new javax.swing.JMenuItem();
        jMenuItemregfaltas = new javax.swing.JMenuItem();
        jMenuferiado = new javax.swing.JMenu();
        jMenuItemferiado = new javax.swing.JMenuItem();
        jMenuconsultas = new javax.swing.JMenu();
        jMenuItemconsentrevistas = new javax.swing.JMenuItem();
        jMenuItemconsrecord = new javax.swing.JMenuItem();
        jMenuItemconsutilidad = new javax.swing.JMenuItem();
        jMenuItemconshorastrab = new javax.swing.JMenuItem();
        jMenuItemconscandidatos = new javax.swing.JMenuItem();
        jMenuItemconsfaltas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuproyectos.setText("Proyectos");

        jMenuItemgestproyectos.setText("Gestionar proyectos");
        jMenuproyectos.add(jMenuItemgestproyectos);

        jMenuItemgestclientes.setText("Gestionar clientes");
        jMenuproyectos.add(jMenuItemgestclientes);

        jMenuItemAsigCand.setText("Asignar Candidatos");
        jMenuproyectos.add(jMenuItemAsigCand);

        jMenuBar1.add(jMenuproyectos);

        jMenucandidato.setText("Candidatos");

        jMenuItemgestcandidato.setText("Gestionar candidatos");
        jMenucandidato.add(jMenuItemgestcandidato);

        jMenuItemgestentrevistas.setText("Gestionar entrevistas");
        jMenucandidato.add(jMenuItemgestentrevistas);

        jMenuBar1.add(jMenucandidato);

        jMenuempleados.setText("Empleados");

        jMenuItemregnomina.setText("Registrar nomina");
        jMenuempleados.add(jMenuItemregnomina);

        jMenuItemregfaltas.setText("Registrar faltas ");
        jMenuempleados.add(jMenuItemregfaltas);

        jMenuBar1.add(jMenuempleados);

        jMenuferiado.setText("Fechas Feriadas");

        jMenuItemferiado.setText("Gestionar fechas");
        jMenuferiado.add(jMenuItemferiado);

        jMenuBar1.add(jMenuferiado);

        jMenuconsultas.setText("Consultas");

        jMenuItemconsentrevistas.setText("Entrevistas");
        jMenuItemconsentrevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemconsentrevistasActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemconsentrevistas);

        jMenuItemconsrecord.setText("Record de pago");
        jMenuItemconsrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemconsrecordActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemconsrecord);

        jMenuItemconsutilidad.setText("Utilidad Obtenida");
        jMenuconsultas.add(jMenuItemconsutilidad);

        jMenuItemconshorastrab.setText("Horas trabajadas ");
        jMenuconsultas.add(jMenuItemconshorastrab);

        jMenuItemconscandidatos.setText("Candidatos");
        jMenuconsultas.add(jMenuItemconscandidatos);

        jMenuItemconsfaltas.setText("Faltas de empleados");
        jMenuconsultas.add(jMenuItemconsfaltas);

        jMenuBar1.add(jMenuconsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemconsentrevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemconsentrevistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemconsentrevistasActionPerformed

    private void jMenuItemconsrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemconsrecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemconsrecordActionPerformed

    public JMenuItem getjMenuItemconscandidatos() {
        return jMenuItemconscandidatos;
    }

    public JMenuItem getjMenuItemconsentrevistas() {
        return jMenuItemconsentrevistas;
    }

    public JMenuItem getjMenuItemconsfaltas() {
        return jMenuItemconsfaltas;
    }

    public JMenuItem getjMenuItemconshorastrab() {
        return jMenuItemconshorastrab;
    }

    public JMenuItem getjMenuItemconsrecord() {
        return jMenuItemconsrecord;
    }

    public JMenuItem getjMenuItemconsutilidad() {
        return jMenuItemconsutilidad;
    }

    public JMenuItem getjMenuItemferiado() {
        return jMenuItemferiado;
    }

    public JMenuItem getjMenuItemgestcandidato() {
        return jMenuItemgestcandidato;
    }

    public JMenuItem getjMenuItemgestclientes() {
        return jMenuItemgestclientes;
    }

    public JMenuItem getjMenuItemgestentrevistas() {
        return jMenuItemgestentrevistas;
    }

    public JMenuItem getjMenuItemgestproyectos() {
        return jMenuItemgestproyectos;
    }

    public JMenuItem getjMenuItemregnomina() {
        return jMenuItemregnomina;
    }

    public JMenuItem getjMenuItemAsigCand() {
        return jMenuItemAsigCand;
    }
    
    public void agregarListener(ActionListener accion){
        
        this.jMenuItemconscandidatos.addActionListener(accion);
        this.jMenuItemconsentrevistas.addActionListener(accion);
        this.jMenuItemconsfaltas.addActionListener(accion);
        this.jMenuItemconshorastrab.addActionListener(accion);
        this.jMenuItemconsrecord.addActionListener(accion);
        this.jMenuItemconsutilidad.addActionListener(accion);
        this.jMenuItemferiado.addActionListener(accion);
        this.jMenuItemgestclientes.addActionListener(accion);
        this.jMenuItemgestentrevistas.addActionListener(accion);
        this.jMenuItemgestproyectos.addActionListener(accion);
        this.jMenuItemregfaltas.addActionListener(accion);
        this.jMenuItemregnomina.addActionListener(accion);
        this.jMenuItemAsigCand.addActionListener(accion);
        this.jMenuItemgestcandidato.addActionListener(accion);
       
            
        
        
        
    }
            

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAsigCand;
    private javax.swing.JMenuItem jMenuItemconscandidatos;
    private javax.swing.JMenuItem jMenuItemconsentrevistas;
    private javax.swing.JMenuItem jMenuItemconsfaltas;
    private javax.swing.JMenuItem jMenuItemconshorastrab;
    private javax.swing.JMenuItem jMenuItemconsrecord;
    private javax.swing.JMenuItem jMenuItemconsutilidad;
    private javax.swing.JMenuItem jMenuItemferiado;
    private javax.swing.JMenuItem jMenuItemgestcandidato;
    private javax.swing.JMenuItem jMenuItemgestclientes;
    private javax.swing.JMenuItem jMenuItemgestentrevistas;
    private javax.swing.JMenuItem jMenuItemgestproyectos;
    private javax.swing.JMenuItem jMenuItemregfaltas;
    private javax.swing.JMenuItem jMenuItemregnomina;
    private javax.swing.JMenu jMenucandidato;
    private javax.swing.JMenu jMenuconsultas;
    private javax.swing.JMenu jMenuempleados;
    private javax.swing.JMenu jMenuferiado;
    private javax.swing.JMenu jMenuproyectos;
    // End of variables declaration//GEN-END:variables
}
